feat(identity): implement from<Sting> for IdOrName
dtantsur/rust-osproto pull request #1
Opened 2019-10-23 18:02 UTC by meltinglava

If we can parse the string as a Id it will return as `IdOrName::id`
else it will be `IdOrName::Name`

ref: [osauth#10](https://github.com/dtantsur/rust-osauth/pull/10)

2019-10-23 18:11 UTC, meltinglava commented
The failing fmt is not code i touched

2019-10-28 10:00 UTC, dtantsur commented
Hi! I've pushed a fix for `cargo fmt`, feel free to rebase.

As to the patch, unfortunately, I don't think it will work this way. The problem is that for a Domain and ID is just a string, e.g. `default`.

2019-11-12 11:12 UTC, dtantsur requested changes

2019-11-12 11:12 UTC, dtantsur commented on src/identity.rs
> +    // example id: 213a290c-ae17-4841-9609-badc01b4ea5c
`default` is a valid keystone domain ID

2019-11-12 11:12 UTC, dtantsur commented on src/identity.rs
> +        if is_id(&unknown) {
I suggest we don't do any guessing and just assume something (we cannot be sure that all IDs are UUIDs, at least keystone domain ID is not). I'd probably go with names.

2021-01-18 08:52 UTC, dtantsur commented
The osproto project will no longer be used. If you'd still like to work on this request, please move it to https://github.com/dtantsur/rust-osauth/

2021-01-18 08:52 UTC, closed without merging